apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        env:
        - name: GF_SERVER_ROOT_URL
          value: "http://metrics.narvii.cn"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "Amino!@#"
      volumes:
      - name: grafana-storage 
        hostPath:
          path: /data/grafana
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitor
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: grafana
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitor
spec:
  rules:
  - host: metrics.narvii.cn
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
