apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:1.7-alpine
        imagePullPolicy: IfNotPresent
        name: influxdb
        ports:
        - containerPort: 8086
        - containerPort: 8083
        env:
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influx-storage
      volumes:
      - name: influx-storage
        hostPath:
          path: /data/influxdb
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitor
  labels:
    app: influxdb
spec:
  ports:
  - name: tcp
    port: 8086
  - name: admin
    port: 8083
  selector:
    app: influxdb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: influxdb
  namespace: monitor
spec:
  rules:
  - host: influxdb.narvii.cn
    http:
      paths:
      - backend:
          serviceName: influxdb
          servicePort: 8083
